// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROYECTOMOVIE.Data;

#nullable disable

namespace PROYECTOMOVIE.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251114190813_AgregarSistemaListas")]
    partial class AgregarSistemaListas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CategoriaPelicula", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeliculasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriasId", "PeliculasId");

                    b.HasIndex("PeliculasId");

                    b.ToTable("CategoriaPelicula");
                });

            modelBuilder.Entity("CategoriaSerie", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriasId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("CategoriaSerie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c040acd-d2fb-43ef-5fc5-c2e3f886ff01",
                            ConcurrencyStamp = "null",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        },
                        new
                        {
                            Id = "3a8e1fdb-7c2d-4a5e-8f1c-9d3b2a1edf5c",
                            ConcurrencyStamp = "null",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Acción"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Comedia"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ciencia Ficción"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Terror"
                        });
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Lista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPublica")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("t_Lista");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.ListaPelicula", b =>
                {
                    b.Property<int>("ListaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAgregada")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListaId", "PeliculaId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("t_ListaPelicula");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enlace_Peli")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Publicada")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenPublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagen_Peli")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Peli")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeliculaPublicId")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Tiempo_Duracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerPublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Video_Trailer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.PlanSubcripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CicloFacturacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("PlanSubcripciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CicloFacturacion = 30,
                            Descripcion = "Ideal para un espectador - 1 pantalla, calidad HD",
                            Nombre = "Plan Básico",
                            Precio = 14.90m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CicloFacturacion = 30,
                            Descripcion = "Perfecto para familias - 3 pantallas, Full HD",
                            Nombre = "Plan Estándar",
                            Precio = 24.90m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CicloFacturacion = 30,
                            Descripcion = "Experiencia cinematográfica - 5 pantallas, calidad 4K",
                            Nombre = "Plan Premium",
                            Precio = 34.90m
                        });
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Enlace_Serie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Publicada")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenPublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagen_Serie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Serie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeriePublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerPublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Video_Trailer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPaymentMethod")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("t_usuario", (string)null);
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.UsuarioPelicula", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calificacion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsFavorita")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAgregada")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vista")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId", "PeliculaId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("t_UsuarioPelicula");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.UsuarioSerie", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SerieId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calificacion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsFavorita")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAgregada")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vista")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId", "SerieId");

                    b.HasIndex("SerieId");

                    b.ToTable("t_UsuarioSerie");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.UsuarioSuscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNotificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MercadoPagoCardId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MercadoPagoPayerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MercadoPagoSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextBillingDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Status", "NextBillingDate");

                    b.ToTable("UsuarioSuscripciones");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.VideoConfigPortada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaConfiguracion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("VideoConfigPortadas");
                });

            modelBuilder.Entity("CategoriaPelicula", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTOMOVIE.Models.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoriaSerie", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTOMOVIE.Models.Serie", null)
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTOMOVIE.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Lista", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.ListaPelicula", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Lista", "Lista")
                        .WithMany("ListaPeliculas")
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTOMOVIE.Models.Pelicula", "Pelicula")
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lista");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.UsuarioPelicula", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Pelicula", "Pelicula")
                        .WithMany("UsuarioPeliculas")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTOMOVIE.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPeliculas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.UsuarioSerie", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Serie", "Serie")
                        .WithMany("UsuarioSeries")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTOMOVIE.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serie");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.UsuarioSuscripcion", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.PlanSubcripcion", "Plan")
                        .WithMany("UsuarioSuscripcion")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PROYECTOMOVIE.Models.Usuario", "Usuario")
                        .WithOne("Subcripcion")
                        .HasForeignKey("PROYECTOMOVIE.Models.UsuarioSuscripcion", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROYECTOMOVIE.Models.Usuario", null)
                        .WithMany("Suscripciones")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Plan");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.VideoConfigPortada", b =>
                {
                    b.HasOne("PROYECTOMOVIE.Models.Pelicula", "Pelicula")
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Lista", b =>
                {
                    b.Navigation("ListaPeliculas");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Pelicula", b =>
                {
                    b.Navigation("UsuarioPeliculas");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.PlanSubcripcion", b =>
                {
                    b.Navigation("UsuarioSuscripcion");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Serie", b =>
                {
                    b.Navigation("UsuarioSeries");
                });

            modelBuilder.Entity("PROYECTOMOVIE.Models.Usuario", b =>
                {
                    b.Navigation("Subcripcion");

                    b.Navigation("Suscripciones");

                    b.Navigation("UsuarioPeliculas");
                });
#pragma warning restore 612, 618
        }
    }
}
